[build]
  publish = "_site"
  command = "eleventy"

# REDIRECT and HEADERS examples

# Redirect rule example
# For more information see:- https://www.netlify.com/docs/netlify-toml-reference/

#[[redirects]]
#  from = "/*"
#  to = "/blog/:splat"
# status = 302



[[redirects]]
  from = "/home/"
  to = "/"

[[plugins]]
package = "@netlify/plugin-sitemap"

  [plugins.inputs]
  buildDir = "_site"
  prettyURLs = true
  trailingSlash = true
  exclude = [

  'https://www.stegglesfactoryshops.com.au/404/',
  'https://www.stegglesfactoryshops.com.au/404.html',
  'https://www.stegglesfactoryshops.com.au/admin/',
  'https://www.stegglesfactoryshops.com.au/admin/email-templates/confirmation.html',
  'https://www.stegglesfactoryshops.com.au/admin/email-templates/email-change.html',
  'https://www.stegglesfactoryshops.com.au/admin/email-templates/invitation.html',
  'https://www.stegglesfactoryshops.com.au/admin/email-templates/confirmation/',
  'https://www.stegglesfactoryshops.com.au/admin/email-templates/email-change/',
  'https://www.stegglesfactoryshops.com.au/admin/email-templates/invitation/'


  
  
  ]

# The default HTTP status code is 301, but you can define a different one e.g.

# Headers rule example
# For more information see:- https://www.netlify.com/docs/netlify-toml-reference/

#[[headers]]
#   Define which paths this specific [[headers]] block will cover.
#   for = "/*"

#[headers.values]
#   X-Frame-Options = "DENY"
#   X-XSS-Protection = "1; mode=block"
#   Content-Security-Policy = "frame-ancestors https://www.facebook.com"

# Redirects and headers are GLOBAL for all builds – they do not get scoped to
# contexts no matter where you define them in the file.
# For context-specific rules, use _headers or _redirects files, which are
# applied on a PER-DEPLOY basis.
